###
GET http://localhost:5085/db

###
GET http://localhost:5085/db/2


###
POST http://localhost:5085/db
Content-Type: application/json

{
    "title":"java",
    "author":"peter",
    "price": 3000,
    "isAvailable": true
}

###
GET http://localhost:5085/book1
